openapi: 3.0.0
info:
  title: Challenge Backend
  description: Backend docs
  version: 1.0.0
  contact:
    email: jooherrera4@gmail.com
    name: Jose

servers:
  - url: http://localhost:3000

tags:
  - name: Home
    description: Home API
  - name: User
    description: Registro y login de usuarios

paths:
  /:
    get:
      tags:
        - Home
      summary: Muestra un mensaje en pantalla
      responses:
        200:
          description: (OK)
  /auth/register:
    post:
      tags:
        - User
      summary: Registra un usuario
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/newUser'

      responses:
        201:
          description: Usuario creado correctamente
        409:
          description: Usuario no disponible
        500:
          description: Problema interno en el servidor
        400:
          description: Formato JSON inválido / No cumple con los parametros requeridos.

components:
  schemas:
    newUser:
      title: Nuevo usuario
      type: object
      required:
        - 'user'
        - 'password'
        - 'email'
      properties:
        user:
          type: string
        password:
          type: string
        email:
          type: string
          format: email
      example:
        user: 'miUsuario'
        password: 'asd123das'
        email: 'email@email.com'
